### ISSUE TITLE
Gem installed via gem install is outdated

### ISSUE THREAD

**Issue by da4nik** [pushhealth/omniauth-doximity_oauth2#1]
If install gem by `gem install` it uses old version which not includes strategy itself. If install gem from github it works. Can you pls update gem ?

**Comment by enddynayn** [comment]
I see. The reason that it does not work when you gem install is that someone else published the gem with the name 'omniauth-doximity_oauth2'. Here is the repo for that gem, https://github.com/indiebrain/omniauth-doximity_oauth2

**Comment by da4nik** [comment]
Right, thank you
